CREATE DATABASE carbon_db;
USE carbon_db;

CREATE TABLE users(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100),
 email VARCHAR(100),
 password VARCHAR(100),
 role VARCHAR(20)
);

CREATE TABLE projects(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100),
 type VARCHAR(50),
 co2 DOUBLE,
 user_id BIGINT
);

CREATE TABLE wallets(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT,
 balance DOUBLE
);

CREATE TABLE orders(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT,
 credits DOUBLE,
 type VARCHAR(10)
);
